name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 2 * * 1"

jobs:
  python-format-black:
    name: Python lint [black]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install black
        run: |
          pip install black>=23

      - name: Lint
        run: black --check ./src/*

  build:
    name: compiling
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: configure
    #  run: ./configure
    
    - name: Install dependencies
      run: |
        pip install psycopg
        pip install pandas
        pip install pyinstaller

    - name: compile mol2db
      run: make mol2db

